# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eea617dc5b58ee7f69bb3849f0be01d285021ca616dee61d200c738326b99797ded000f79eef51b1751b25201d3a0fcadc3ca8e2e1cd709de04c597f80288b2

test:
  secret_key_base: 8cd6abba10b2ce0090572d9c2dff739103d58ee33ca8213a97483bcc86721faf53ffd964ec562306ce630bcca57b9cc96b77332697fe497d81c78ba29823c419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
